apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${DEPLOYMENT}
  labels:
    app: ${DEPLOYMENT}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${DEPLOYMENT}
  template:
    metadata:
      labels:
        app: ${DEPLOYMENT}
    spec:
      containers:
      - name: ${CONTAINER}
        image: ${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: ${CONTAINER_PORT}
      imagePullSecrets:
      - name: ${GITLAB_REGISTRY_CREDENTIALS}