apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE}
  labels:
    app: ${SERVICE}
spec:
  type: LoadBalancer
  ports:
  - port: ${EXPOSED_PORT}
    targetPort: ${CONTAINER_PORT}
    protocol: TCP
  selector:
    app: ${DEPLOYMENT}
